import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch, faMapMarkerAlt, faClock, faUserCircle } from '@fortawesome/free-solid-svg-icons';
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import localFont from 'next/font/local';
import { Analytics } from "@vercel/analytics/react"
import BackgroundMusic from './components/BackgroundMusic';
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

const pretendard = localFont({
  src: '../../public/fonts/Pretendard-Regular.woff',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Gmarket+Sans:wght@700&family=Montserrat:wght@800&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className} ${pretendard.className}`}
      >
        {children}
        <Footer />
        <Analytics />
        <BackgroundMusic />
      </body>
    </html>
  );
}
